version: '3.3'
services:
  postgres:
    image: postgres:14
    restart: always
    env_file:
      - '.env'
    environment:
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    expose:
      - 5432
volumes:
  postgres:
    driver: local