version: '3.3'
services:
  postgres:
    image: postgres:14
    restart: always
    # env_file:
    #   - .env
    environment:
    # - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=dailee
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=root@admin.com
     - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
volumes:
  postgres:
    driver: local